driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  # The below boxes are shared via VagrantCloud. Until kitchen-vagrant is
  # updated you'll need to add the box manually:
  #
  #   vagrant box add chef/solaris-10.11
  #
  # Please note private boxes will require a `vagrant login` for this to work.
  - name: solaris-10.11
    driver:
      box: chef/solaris-10.11 # private

suites:
  - name: pkgutil_package_install
    run_list: pkgutil_package::install
  - name: pkgutil_package_remove
    run_list: pkgutil_package::remove
